meta:
  title: my-book
  author: 'Yourname GoesHere'
  description: 'My book is amazing and stuff!'
  isbn-13: 123456789101
  isbn-10: 123456789
  publisher: World Uniting Press
  date: 2023-05-01T00:00:00.000Z
  language: en
  lccn: 123456789
  subject: Non-fiction
  rights: All Rights Reserved
settings:
  entryfile: index.md.ejs
ejs-options:
  await: true
  preprocessor-include: null
  delimiter: null