# https://bit.ly/github-issue-forms
name: Errata (Error) Report
description: Report an Edit
title: "[Edit]: "
labels: "edit :pencil2:"
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I have read the [Contributing Guidelines](https://github.com/worlduniting/bookpub/blob/main/CONTRIBUTING.md) for this project.
        required: true
      - label: I agree to follow the [Code of Conduct](https://github.com/worlduniting/bookpub/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
        required: true
      - label: I have searched the [issue tracker](https://www.github.com/worlduniting/bookpub/issues) for a bug report that matches the one I want to file, without success.
        required: true
- type: input
  attributes:
    label: Book Version
    description: |
      What version of your book is this?
    placeholder: 0.1.0
  validations:
    required: true
- type: checkboxes
  id: book-format
  attributes:
    label: Which book format are you referencing?
    description: You may select more than one.
    options:
      - label: HTML
      - label: PDF
      - label: Print (PDF)
      - label: Epub (Most eReaders)
      - label: MOBI (Amazon eReaders)
      - label: Audio Book
- type: dropdown
  attributes:
    label: What format are you referencing?
    options:
      - HTML
      - PDF
      - Print (PDF)
      - EPub (Most eReaders)
      - MOBI (Amazon Readers)
      - Audio Book
  validations:
    required: true
- type: input
  attributes:
    label: Location of Edit
    description: What page, paragraph and line is the error?
    placeholder: p21-p4-l3
  validations:
    required: true
- type: dropdown
  attributes:
    label: What kind of content?
    options:
      - Misspelling
      - Grammar
      - Word Choice
      - Factual Inconsistency
      - Layout
      - Image
      - Footnote
  validations:
    required: true
- type: textarea
  attributes:
    label: What is the error?
    description: A clear and concise description of the error you see.
  validations:
    required: true
- type: textarea
  attributes:
    label: How should it be fixed?
    description: A clear description of your suggested change.
    required: true