# https://bit.ly/github-issue-forms
name: "Book Errata (Error) Report :pencil2:"
description: Report an Edit
title: "[Errata-Report]: "
labels: ["book errata :pencil2:"]
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I have read the [Contributing Guidelines](https://github.com/worlduniting/bookpub/blob/main/CONTRIBUTING.md) for this project.
        required: true
      - label: I agree to follow the [Code of Conduct](https://github.com/worlduniting/bookpub/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
        required: true
      - label: I have searched the [issue tracker](https://www.github.com/worlduniting/bookpub/issues) for a bug report that matches the one I want to file, without success.
        required: true

- type: dropdown
  attributes:
    label: What is the version of the book/project? (look in colophon)
    options:
      - ~0.2.0 (current)
      - ~0.1.0
  validations:
    required: true


- type: dropdown
  attributes:
    label: Book Version
    description: |
      What version of your book is this?
    placeholder: 0.1.0
  validations:
    required: true
- type: checkboxes
  id: book-format
  attributes:
    label: Which book format are you referencing?
    description: You may select more than one.
    options:
      - label: HTML
      - label: PDF
      - label: Print (PDF)
      - label: Epub (Most eReaders)
      - label: MOBI (Amazon eReaders)
      - label: Audio Book
- type: input
  attributes:
    label: Location of Error/Edit
    description: On what page, paragraph and line is the error (use format page(s)paragraph(s).line(s) (e.g. 121.4-6.all)? If you know the manuscript source file and line (file.md.ejs ln21).
    placeholder: (pp.pg.ln) or (file ln)
  validations:
    required: true
- type: dropdown
  attributes:
    label: What kind of content?
    options:
      - Misspelling
      - Grammar
      - Word Choice
      - Factual Inconsistency
      - Layout
      - Image
      - Source (Footnote/Ref/Index)
  validations:
    required: true
- type: textarea
  id: error-content
  attributes:
    label: What is the error?
    description: A clear and concise description of the error you see.
    placeholder: Please quote or describe the incorrect content!
  validations:
    required: true
- type: textarea
  id: suggested-fix
  attributes:
    label: How should it be fixed?
    description: A clear description of your suggested change.
    placeholder: Please tell us your suggested change!
  validations:
    required: true